# Generated by Django 5.0.2 on 2024-02-15 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='color',
        ),
    ]
