# Generated by Django 5.0.2 on 2024-02-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='division',
        ),
    ]
