# Generated by Django 5.0.2 on 2024-02-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typetask',
            options={'verbose_name': 'Статус заявки', 'verbose_name_plural': 'Статусы заявок'},
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
