# Generated by Django 5.0.2 on 2024-02-15 05:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_status_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=colorfield.fields.ColorField(default='rgb(255, 255, 255)', image_field=None, max_length=25, samples=None),
        ),
    ]
