# Generated by Django 5.0.2 on 2024-02-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.task', verbose_name='Заявка'),
        ),
    ]
