# Generated by Django 5.0.2 on 2024-03-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_options'),
        ('user', '0002_alter_department_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_org', to='user.organization', verbose_name='Организация'),
        ),
    ]
