# Generated by Django 5.0.2 on 2024-02-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_typetask_options_delete_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typetask',
            options={'verbose_name': 'Тип заявки', 'verbose_name_plural': 'Типы заявок'},
        ),
    ]
