# Generated by Django 5.0.2 on 2024-02-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_status_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_reaction',
        ),
    ]
