# Generated by Django 5.0.2 on 2024-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_plan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок исполнении'),
        ),
    ]
