# Generated by Django 5.0.2 on 2024-02-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_typetask_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sostoyan',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
