# Generated by Django 5.0.2 on 2024-03-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_date_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='organization',
        ),
    ]
