# Generated by Django 5.0.2 on 2024-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sostoyan',
            field=models.CharField(blank=True, max_length=8, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Статус'),
        ),
    ]
