# Generated by Django 5.0.2 on 2024-02-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('task', '0003_remove_task_division'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='division',
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='user.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auth.group', verbose_name='Роль'),
        ),
        migrations.DeleteModel(
            name='Division',
        ),
    ]
