# Generated by Django 5.0.2 on 2024-02-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_telegramid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegramid',
            field=models.IntegerField(verbose_name='id телеграмм пользователя'),
        ),
    ]
