# Generated by Django 5.0.2 on 2024-02-15 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
    ]
