# Generated by Django 5.0.2 on 2024-02-16 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0003_remove_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auth.group', verbose_name='Должность'),
        ),
    ]
