# Generated by Django 5.0.2 on 2024-02-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_telegramid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegramid',
            field=models.CharField(null=True, verbose_name='id телеграмм пользователя'),
        ),
    ]
