# Generated by Django 5.0.2 on 2024-03-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_first_name_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.AddField(
            model_name='organization',
            name='INN',
            field=models.CharField(max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='organization',
            name='KPP',
            field=models.CharField(max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(max_length=13, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='organization',
            name='yur_adres',
            field=models.CharField(max_length=255, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Полное наименование организации'),
        ),
    ]
