# Generated by Django 5.0.2 on 2024-03-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_organization_description_organization_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, null=True, verbose_name='Должность'),
        ),
    ]
